### ISSUE TITLE
Doesn't seem to work with Processing 3.4

### ISSUE THREAD

**Issue by Marcao8** [anachrocomputer/LineCamera#1]
Hello there,
don't think Repo will be updated anymore but anyways, the processing sketch throws out 2 lines and doesnt refresh. Even some green pixels involved.
If anyone has some ideas about it, I'm glad to read them.
Here is how it's lookingon my side: https://i.imgur.com/6Q7ynvJ.png

**Comment by anachrocomputer** [comment]
OK, thanks for letting me know. I haven't run this code for years, so it's likely to be a bit out-of-date. Have you tried to do any diagnostics? If I have time/motivation, I'll take a look at it.

**Comment by Marcao8** [comment]
No, I've switched to an even simpler code(see: https://github.com/ap-tech/Getting-started-with-the-TSL1401CL-linescan-camera-with-arduino-and-processing.- ). But thank you for taking the time.
